version: '3.8'
services:
  login:
    build: .
    
    command: python3 -u login.py
    ports:
      - "3000:3000"
    links:
      - db
  signup:
    build: .
    command: python3 -u signup.py
    ports:
      - "3001:3001"
    links:
      - db
  db:
    image: mongo:latest
    hostname: project_mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=pass
    ports:
      - 27017:27017
